version: '3.8'

services:

  app:
    build: ./
    environment:
      - DATABASE_URL=postgresql://postgres:F00B4RYY@postgres:5432/siralim_ultimate_api
      - PORT=8000
    volumes:
      - ./:/code
    networks:
      - app
      - postgres
      - redis

  postgres:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=F00B4RYY
      - POSTGRES_DB=siralim_ultimate_api
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  redis:
    image: redis:6.2.5
    networks:
      - redis

volumes:
  postgres:

networks:
  app:
  postgres:
  redis: