name: siralim-ultimate-api-ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: ./commands/dev-bootstrap
      - name: Lint Check
        run: ./commands/lint-check
      - name: Test
        run: ./commands/test
  ecr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        run: |
          # Build a docker container and push it to ECR 
          GIT_BRANCH=${GITHUB_REF##*/}
          LATEST_TAG=${ECR_REGISTRY}/${ECR_REPOSITORY}:${GIT_BRANCH}-latest
          GIT_SHA_TAG=${ECR_REGISTRY}/${ECR_REPOSITORY}:${GIT_BRANCH}-${GITHUB_SHA}

          echo "Building ${GIT_SHA_TAG}"
          docker build -t $GIT_SHA_TAG .
          
          echo "Pushing ${LATEST_TAG}"
          docker push $GIT_SHA_TAG

          echo "Pushing ${LATEST_TAG}"
          docker tag $GIT_SHA_TAG $LATEST_TAG
          docker push $LATEST_TAG
            