name: siralim-ultimate-api-ci
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        repository: 'rovermicrover/siralim-ultimate-dev'
      - uses: actions/checkout@v2
        path: ./siralim-ultimate-api
      - name: Build the stack
        run: ./commands/dev-bootstrap
      - name: Lint Check
        run: ./commands/app/lint-check
      - name: Test
        run: ./commands/app/test