name: siralim-ultimate-api-ci
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: ./commands/dev-bootstrap
      - name: Lint Check
        run: ./commands/lint-check
      - name: Test
        run: ./commands/test